# Ansible managed
---
version: "2"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Delt@Vict0r1
      - MYSQL_DATABASE=luckperms
      - MYSQL_USER=kumpdevluckperms
      - MYSQL_PASSWORD=Delt@Vict0r1
    restart: unless-stopped
