---
# Run command below to run playbook
# ansible-playbook --ask-vault-pass playbook.yml

- hosts: localhost
  vars_files:
    - 'vars/vault.yaml'
  roles:
#    - role: geerlingguy.docker
    - role: ironicbadger.ansible_role_docker_compose_generator
  tasks:
  - name: Ensure required directories are created
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - mc-waterfall-proxy
      - lobby
  - name: Configure waterfall proxy
    template:
      src: templates/waterfall-config.yml.j2
      dest: mc-waterfall-proxy/config.yml
      owner: "{{ docker_compose_generator_uid }}"
      group: "{{ docker_compose_generator_gid }}"
  - name: Configure luckperms for the paper/spigot servers
    template:
      src: templates/luckperms-config.yml.j2
      dest: "{{ item }}/plugins/LuckPerms/config.yml"
      owner: "{{ docker_compose_generator_uid }}"
      group: "{{ docker_compose_generator_gid }}"
    loop:
      - lobby
