---
# geerlingguy.docker
docker_users:
  - kump

# variables for mc-waterfall-proxy configuration
proxy_motd: "&3Kumpdev Ansible Testbed!"
proxy_priority_server: "lobby"

# Variables that are used in configuration below
mc_connection_port: 25565
mc_version: "1.16.3"
mc_ops: "Kumpy"
mc_whitelisted_players: "Kumpy,Fett32"  # players should be listed separated by commas

# ironicbadger.docker_compose_generator
containers:
# This container is used for the luckperms database so that the server network has one central permissions system.
# This prevents the admin from having to update permissions on all servers individually
  - service_name: luckperms-mariadb
    image: mariadb
    # active: determines whether or not container is included in resulting docker-compose file
    active: true
    environment:
      # these vars are stored in vars/vault.yaml using ansible-vault
      - "MYSQL_ROOT_PASSWORD={{ mysql_root }}"
      - "MYSQL_DATABASE={{ mysql_db }}"
      - "MYSQL_USER={{ mysql_user }}"
      - "MYSQL_PASSWORD={{ mysql_pass }}"
    volumes:
      - "./luckperms-mariadb/mysql:/var/lib/mysql"
    restart: unless-stopped
# This container is the waterfall proxy, it handles player connections to all servers in the network
  - service_name: mc-waterfall-proxy
    image: itzg/bungeecord
    active: true
    environment:
      - "TYPE=WATERFALL"
    ports:
      - "{{ mc_connection_port}}:25577"
    volumes:
      - "./mc-waterfall-proxy/config.yml:/config/config.yml"
      - "./mc-waterfall-proxy/plugins:/plugins"
    restart: unless-stopped
# This container is the first server you login to, it acts as a hub to access the other servers
  - service_name: lobby
    image: itzg/minecraft-server
    active: true
    environment:
      - "TYPE=PAPER"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=512M"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=peaceful"
      - "PVP=false"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=10000"
      - "WHITELIST={{ mc_whitelisted_players }}"
      - "PLUGINS_SYNC_UPDATE=false"
    volumes:
      - "./plugins:/plugins"
      - "./lobby:/data"
    restart: unless-stopped
