---
# geerlingguy.docker
docker_users:
  - $USER

# variables for mc-waterfall-proxy configuration
proxy_motd: "&3Kumpdev Ansible Testbed!"
proxy_priority_server: "lobby"

# Variables that are used in configuration below
mc_connection_port: 25565
mc_version: "1.16.3"
mc_ops: "Kumpy"
mc_whitelisted_players: "Kumpy,Fett32"  # players should be listed separated by commas

# ironicbadger.docker_compose_generator
docker_compose_generator_output_path: "."

containers:
# This container is used for the luckperms database so that the server network has one central permissions system.
# This prevents the admin from having to update permissions on all servers individually
  - service_name: luckperms-mariadb
    image: mariadb
    # active: determines whether or not container is included in resulting docker-compose file
    active: true
    environment:
      # these vars are stored in vars/vault.yaml using ansible-vault
      - "MYSQL_ROOT_PASSWORD={{ mysql_root }}"
      - "MYSQL_DATABASE={{ mysql_db }}"
      - "MYSQL_USER={{ mysql_user }}"
      - "MYSQL_PASSWORD={{ mysql_pass }}"
    volumes:
      - "./data/luckperms-mariadb/mysql:/var/lib/mysql"
    restart: unless-stopped
# This container is the waterfall proxy, it handles player connections to all servers in the network
  - service_name: mc-waterfall-proxy
  # Refer to itzg/docker-bungeecord github for documentation on env variables and container configuration below
    image: itzg/bungeecord
    active: true
    environment:
      - "TYPE=WATERFALL"
    ports:
      - "{{ mc_connection_port}}:25577"
    volumes:
      - "./data/mc-waterfall-proxy/config.yml:/config/config.yml"
      - "./data/mc-waterfall-proxy/plugins:/plugins"
    restart: unless-stopped
# This container is the first server you login to, it acts as a hub to access the other servers
# Ensure that the server type is always the first environment variable for proper configuration
  - service_name: lobby
  # Refer to itzg/docker-minecraft-server github for documentation on env variables and container configuration below
    image: itzg/minecraft-server
    active: true
    environment:
      - "TYPE=PAPER"
      - "SERVER_NAME=lobby"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=512M"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=peaceful"
      - "PVP=false"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=100"
      - "WHITELIST={{ mc_whitelisted_players }}"
      - "PLUGINS_SYNC_UPDATE=false"
    # List plugins to download below
      - "MODS=https://ci.lucko.me/job/LuckPerms/1173/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.2.8.jar"
    volumes:
    # Optional method to install plugins on server. Add .jar files to ./plugins directory
    # The downside to this option is that they cannot auto update
      - "./plugins:/plugins"
      - "./data/lobby:/data"
    restart: unless-stopped
  - service_name: fabric
    image: itzg/minecraft-server
    active: true
    environment:
      - "TYPE=FABRIC"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=1G"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=normal"
      - "PVP=true"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=10000"
      - "WHITELIST={{ mc_whitelisted_players }}"
      - "PLUGINS_SYNC_UPDATE=false"
    # List mods to download below"
      - "MODS=https://github.com/OKTW-Network/FabricProxy/releases/download/v1.3.3/FabricProxy-1.3.3.jar"
    volumes:
      - "./data/fabric:/data"
    restart: unless-stopped
