name: docker-compose-github-actions
on: [push]
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BSFishy/pip-action@v1
        with:
          packages: docker
      - run: ansible-galaxy install -r requirements.yml
      - run: ansible-galaxy collection install community.general
      - run: echo ${{ secrets.VAULT_PASS }} >> .vault_pass.txt
      - run: ansible-playbook --vault-password-file .vault_pass.txt playbook.yml
